global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: auth
    static_configs:
      - targets: ["auth-service:8005"]

  - job_name: business
    static_configs:
      - targets: ["business-service:8001"]

  - job_name: booking
    static_configs:
      - targets: ["booking-service:8002"]

  - job_name: payment
    static_configs:
      - targets: ["payment-service:8003"]

  - job_name: analytics
    static_configs:
      - targets: ["analytics-service:8004"]
