apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: PROMETHEUS_DS
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
  dashboards.yml: |
    apiVersion: 1

    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
