apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: booking
resources:
  - namespace.yaml
  - configmap-prometheus.yaml
  - configmap-grafana.yaml
  - configmap-grafana-dashboards.yaml
  - configmap-frontend-nginx.yaml
  - configmap-locust.yaml
  - mongo.yaml
  - redis.yaml
  - auth-service.yaml
  - business-service.yaml
  - booking-service.yaml
  - payment-service.yaml
  - analytics-service.yaml
  - notification-service.yaml
  - gateway.yaml
  - frontend.yaml
  - prometheus.yaml
  - grafana.yaml
  - locust.yaml
  - ingress.yaml
