namespace: booking

# Terraform + SSH
terraform_dir: "{{ playbook_dir }}/../../terraform"
ssh_user: ubuntu
ssh_private_key_path: "{{ lookup('env', 'SSH_KEY_PATH') | default('', true) }}"

# Kubernetes bootstrap
k8s_minor_version: "v1.29"
kubeadm_api_version: "kubeadm.k8s.io/v1beta3"
pod_cidr: "10.244.0.0/16"
cni_manifest: "https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"
install_local_path_provisioner: true
local_path_manifest: "https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml"
allow_control_plane_schedule: true

# Deployment
k8s_local_dir: "{{ playbook_dir }}/../../../k8s"
kustomize_dir: "/home/{{ ssh_user }}/booking-k8s"
install_ingress_controller: false
ingress_controller_manifest: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml"

deployments:

  - mongo
  - redis
  - auth-service
  - business-service
  - booking-service
  - payment-service
  - analytics-service
  - notification-service
  - gateway
  - frontend
  - prometheus
  - grafana
  - locust
